apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test  # Consistent indentation
  name: francistestdriver
spec:
  # Number of replicas is missing, assuming you want to deploy at least one
  replicas: 0  # Add this line

  selector:
    matchLabels:
      environment: test  # Selector for identifying pods to manage

  # Deployment strategy configuration is missing
  strategy: {}  # Add this line

  template:
    metadata:
      labels:
        environment: test  # Labels for the pods

    spec:
      containers:
      - name: nginx  # Container name
        image: nginx:1.17  # Container image
